version: "3"
services:
  as-proxy:
    image: cloudstateio/cloudstate-proxy-core:latest
    command: -Dconfig.resource=dev-mode.conf -Dcloudstate.proxy.protocol-compatibility-check=false
    ports:
      - "9000:9000"
    environment:
#[[      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}]]#
