version: "3"
services:
  as-proxy:
    image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.7.0-beta.1
    command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.protocol-compatibility-check=false
    ports:
      - "9000:9000"
    environment:
#[[      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}]]#
