version: "3"
services:
  # note the ports being different than other sample docker-compose to allow this service to run
  # on the same local machine as the scala-customer-registry-
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.0.26
    command: -Dconfig.resource=dev-mode.conf -Dkalix.proxy.eventing.support=google-pubsub-emulator
    ports:
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8081}
      PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
  gcloud-pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:341.0.0
    command: gcloud beta emulators pubsub start --project=test --host-port=0.0.0.0:8086
    ports:
      - 8085:8085
