
# If you're looking to use eventing with Google PubSub, to get an emulator running:
# - uncomment property "-Dkalix.proxy.eventing.support=google-pubsub-emulator"
# - uncomment the env var PUBSUB_EMULATOR_HOST and the section below for gcloud-pubsub-emulator service
version: "3"
services:
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.6
    command: -Dconfig.resource=dev-mode.conf -Dlogback.configurationFile=logback-dev-mode.xml #-Dkalix.proxy.eventing.support=google-pubsub-emulator
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}
      # Comment to enable ACL check in dev-mode (see https://docs.kalix.io/services/using-acls.html#_local_development_with_acls)
      ACL_ENABLED: "false"
      # Uncomment to enable advanced view features locally (note: disabled in deployed services by default)
      #VIEW_FEATURES_ALL: "true"
      # Uncomment to disable the JWT dev secret
      #JWT_DEV_SECRET: "false"
      # Uncomment to set the JWT dev secret issuer
      #JWT_DEV_SECRET_ISSUER: "my-issuer"
      # Uncomment if using pubsub emulator
      #PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
  #gcloud-pubsub-emulator:
  #  image: gcr.io/google.com/cloudsdktool/cloud-sdk:341.0.0
  #  command: gcloud beta emulators pubsub start --project=test --host-port=0.0.0.0:8085
  #  ports:
  #    - 8085:8085

