version: "3"
services:
  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.1.35
    container_name: tracing
    ports:
      - "${ADVERTISED_HTTP_PORT}:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dkalix.proxy.telemetry.tracing.enabled=true
        -Dkalix.proxy.telemetry.tracing.collector-endpoint=http://jaeger:4317
      ADVERTISED_HTTP_PORT: ${ADVERTISED_HTTP_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - 4317:4317
      - 16686:16686
