name: Test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: akkaserverless-codegen
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Maven/Java tooling
        uses: actions/checkout@v2
        with:
          repository: lightbend/akkaserverless-maven-java
          path: akkaserverless-maven-java
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Clone Maven/Java tooling
        uses: actions/checkout@v2
        with:
          repository: lightbend/akkaserverless-npm-js
          path: akkaserverless-npm-js
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Run tests
        # The it:test task compiles, runs unit tests, and then runs integration tests
        run: sbt it:test
        working-directory: ./akkaserverless-codegen
